spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8086/realms/gestao-financeira
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8086/realms/gestao-financeira/protocol/openid-connect/certs

keycloak.server-url=http://localhost:8086