spring.application.name=batch

spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_financeira
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true

api.transacoes.url.nubank=http://localhost:9001/nubank
api.transacoes.url.inter=http://localhost:9002/inter
api.transacoes.url.willbank=http://localhost:9003/willBank
server.port=8081
